# Generated by Django 3.1 on 2020-08-29 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='user',
        ),
        migrations.CreateModel(
            name='UsuarioTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamientos.tratamiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tratamientos.respuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='usuario_tratamiento',
            field=models.ManyToManyField(through='tratamientos.UsuarioTratamiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
